version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: viethung
      RABBITMQ_DEFAULT_PASS: viethung1712
    networks:
      - api_network
  db:
    image: postgres:15-alpine
    container_name: "postgresql"
    expose:
      - 5432
    environment:
      POSTGRES_USER: viethung
      POSTGRES_PASSWORD: viethung1712
      POSTGRES_DB: social
    networks:
      - api_network
  api:
    build: ./api
    container_name: "fastapi"
    volumes:
      - ./api:/app
    environment:
      HOST: 0.0.0.0
      PORT: 80
      RELOAD: 1
      CELERY_BROKER_URL: amqp://viethung:viethung1712@rabbitmq:5672/
      POSTGRES_USER: viethung
      POSTGRES_PASSWORD: viethung1712
      POSTGRES_DB: social
    ports:
      - 8000:80
    networks:
      - api_network
    depends_on:
      - rabbitmq
      - db
  worker:
    container_name: "worker"
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    command: celery --app api_celery.worker.celery worker --concurrency=4 --loglevel=info
    networks:
      - api_network
    environment:
      HOST: 0.0.0.0
      PORT: 80
      RELOAD: 1
      CELERY_BROKER_URL: amqp://viethung:viethung1712@rabbitmq:5672/
      POSTGRES_USER: viethung
      POSTGRES_PASSWORD: viethung1712
      POSTGRES_DB: social
    depends_on:
      - rabbitmq
      - db
      - api

networks:
  api_network:
    driver: bridge